/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1I7dtbONHBp
 */
"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { useCartContext } from "../context/CartContext";
import Link from "next/link";

export function CartComponent() {

  const { cart, totalQty } = useCartContext()
  //console.log(totalQty());

  return (
    <Button className="relative mr-4" variant="outline"  >
      <Link href={`/carrito`}>
        <ShoppingCartIcon className="h-4 w-4" />
        <Badge className="absolute top-0 right-0 transform translate-x-[50%] translate-y-[-50%] bg-red-500 text-white">
          {totalQty()}
        </Badge>
      </Link>
    </Button>
  )
}


function ShoppingCartIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}
